# Generated by Django 5.1.5 on 2025-02-10 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0005_commande'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commande',
            unique_together={('client', 'produit')},
        ),
    ]
