# Generated by Django 5.1.5 on 2025-02-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0006_alter_commande_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commande',
            unique_together=set(),
        ),
    ]
